# Generated by Django 6.0.6 on 2026-06-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_weeklyslottemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyslottemplate',
            options={'ordering': ['day_of_week', 'sort_order', 'start_time']},
        ),
        migrations.AddField(
            model_name='slottemplate',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklyslottemplate',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklyslottemplate',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
